services:
  claudio:
    image: ${IMAGE:-claudio:latest}
    build:
      context: .
      dockerfile: Dockerfile
    platform: ${PLATFORM:-linux/amd64}
    container_name: ${STABLE_HOSTNAME:-claudio}
    env_file: .env
